### ISSUE TITLE
Duplicate HeartStopper is maybe Subterfuge Mask 

### ISSUE THREAD

**Issue by RacingRotary** [andrej2431/poe-2-skill-tree-planner#2]
https://imgur.com/a/pamQwjZ

The 2nd (right-most) Heartstopper shape is close to what is shown in Dreamcore video as Subterfuge Mask.

Source has same issue 
https://marcoaaguiar.github.io/poe2-tree/

**Comment by andrej2431** [comment]
ok, i've changed it
