### ISSUE TITLE
Ascendancy drop down won't let me change to a different asecendancy

### ISSUE THREAD

**Issue by LeonChadwick** [andrej2431/poe-2-skill-tree-planner#6]
I try to use the ascendancy drop down at top and it ignore my change.

**Comment by LeonChadwick** [comment]
After creating a new tree the drop down starts to work.
It even then works when I go back to the "0" tree which is the default, so its a bug just with the initial first tree default.

**Comment by andrej2431** [comment]
This is fixed now, though there might still be some issues with the first tree
